### ISSUE TITLE
Unable to launch Smart Tomcat with Tomcat 9, conf files not found

### ISSUE THREAD

**Issue by GiraffeLand** [zengkid/SmartTomcat#115] opened 2023-10-16 09:17 UTC
**Describe the bug**
Hello, whenever I decide to run my projet locally with a Tomcat 9, it just won't start. The build goes through no problem but I get an error right after according to which the plugin doesn't find the conf files in the indicated folder (User folder). The issue is that the folder is created but is indeed empty. Whenever I try to add any conf files like a server.xml file, the plugin deletes it and then complains the folder is empty. 

Running the projet with Tomcat 7 however seems to be working. I have no understanding why. But it happens everytime I launch the project. I am either doing something wrong or the plugin has a bug. 

I remember being able to run my project with Tomcat 9 a few weeks ago though, and downgrading the plugin didn't work either.

Thanks.

**Screenshots**
![2023-10-16 11_09_10-paysage-web – paysage properties  paysageWeb-slr-web](https://github.com/zengkid/SmartTomcat/assets/148053908/81976609-b37e-45f5-b8fc-6861e4a0df75)

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**
IntelliJ IDEA 2023.2.3 (Community Edition)
Build #IC-232.10072.27, built on October 11, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Registry:
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.ideolog (222.1.0.0)
    color.scheme.Dark Blue Theme (0.1)
    Batch Scripts Support (1.0.13)
    com.github.aslbarnett.lapisjetbrains (2.0.0)
    com.jetbrains.space (232.10072.29)
    EclipseCodeFormatter (23.2.223.000.0-Eclipse_2023-03)
    camtwoTomcatRunner (1.7)
    com.poratu.idea.plugins.tomcat (4.7.0)
    org.bugzilla.tasks (0.1)
    com.dubreuia.tool (2.6.2)
    dev.flikas.idea.spring.boot.assistant.plugin (222.17.2)
    DBN (3.4.1620.0)
    com.xstudio.com.xstudio.plugin.idea (1.0.18)
    mobi.hsz.idea.gitignore (4.5.2)
    org.sonarlint.idea (9.1.0.75538)

Kotlin: 232-1.9.0-IJ10072.27

**Comment by tb12315** [comment] 2023-10-16 09:17
你发的邮件我已经收到。会在近期内查看。

**Comment by yuezk** [comment] 2023-10-16 09:51
@GiraffeLand Have you ever tried to re-create the SmartTomcat Configuration?

**Comment by yuezk** [comment] 2023-10-16 09:52
And ensure that the Tomcat server you choose has the `conf` folder with contents.

**Comment by yuezk** [comment] 2023-10-16 09:56
As the code shows, the plugin will clear the `conf` folder and copy the content from the Tomcat server.

https://github.com/zengkid/SmartTomcat/blob/82bfe29b46d53249adbc7f5a63a92ff6f597e22b/src/main/java/com/poratu/idea/plugins/tomcat/conf/TomcatCommandLineState.java#L122-L125

**Comment by GiraffeLand** [comment] 2023-10-16 12:49
> @GiraffeLand Have you ever tried to re-create the SmartTomcat Configuration?

I did, removed the whole .SmartTomcat folder and it was recreated, but with the same issue.

> And ensure that the Tomcat server you choose has the `conf` folder with contents.

Ultimately I managed to trace which Tomcat was used and I updated the conf folder, now it does start. Though I am getting a InvocationError, coming from this file not being present. I actually tried to add the file manually it still won't work.

![2023-10-16 14_46_29-paysage-web – paysage properties  paysageWeb-slr-web](https://github.com/zengkid/SmartTomcat/assets/148053908/266b088d-3310-49d4-bfbf-25e7541692dd)

At the end of the day, this is another problem, so I could open another ticket and close this one if needed.

**Comment by yuezk** [comment] 2023-11-06 02:01
@GiraffeLand Sorry for the late response. But I couldn't find what was wrong with the error log.

**Comment by YSHG666888** [comment] 2024-02-03 14:35
I also exist the same problem

**Comment by yuezk** [comment] 2024-02-05 01:48
@YSHG666888 Can you give more details about your problem?

**Comment by YSHG666888** [comment] 2024-02-07 10:44
I already know the cause of the problem, because the configuration file in the Apache tomcat 9.0.85 I downloaded is missing, so the configuration of Smart Tomcat copied to the C drive is also missing. The solution is to download Apache tomcat again and reconfigure the Tomcat Server in IDEA

**Comment by yuezk** [comment] 2024-02-07 11:03
> because the configuration file in the Apache tomcat 9.0.85 I downloaded is missing

Did you download it from the official website?

**Comment by yuezk** [comment] 2024-02-10 04:09
Closing.

**Closed by yuezk** 2024-02-10 04:09 UTC
Labels: bug
