### ISSUE TITLE
Version 3.0 is not comapatible with the latest IDEA community version

### ISSUE THREAD

**Issue by yuezk** [zengkid/SmartTomcat#26] opened 2019-09-25 04:28 UTC
## IDEA version
```
IntelliJ IDEA 2019.2.2 (Community Edition)
Build #IC-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true
Non-Bundled Plugins: IdeaVIM, JettyRunner-GK, com.alayouni.ansiHighlight, com.intellij.ideolog, com.your.company.unique.plugin.id, com.cybrosis.catdea, training, zielu.gittoolbox
```

## Smart Tomcat version

Version: 3.0

I cannot find this plugin in the plugin preference panel, so I have to download it from the [plugin site](https://plugins.jetbrains.com/plugin/9492-smart-tomcat/versions) manually and install it from disk. And I got this error when I was trying to install it.

![image](https://user-images.githubusercontent.com/3297602/65569369-f4175d00-df8f-11e9-996a-f0a2d2406fc3.png)

**Comment by zengkid** [comment] 2019-09-27 15:21
Hi, Kevin Yue


In plugins site, I find only support 2019.1.1 C 2019.1.4 version. Should be fixed the issue.
[cid:image003.png@01D5758A.47DC8A70]

Regards
Yi

________________________________
发件人: Kevin Yue <notifications@github.com>
发送时间: Wednesday, September 25, 2019 12:28:37 PM
收件人: zengkid/SmartTomcat <SmartTomcat@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [zengkid/SmartTomcat] Version 3.0 is not comapatible with the latest IDEA community version (#26)

IDEA version

IntelliJ IDEA 2019.2.2 (Community Edition)
Build #IC-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true
Non-Bundled Plugins: IdeaVIM, JettyRunner-GK, com.alayouni.ansiHighlight, com.intellij.ideolog, com.your.company.unique.plugin.id, com.cybrosis.catdea, training, zielu.gittoolbox


Smart Tomcat version

Version: 3.0

I cannot find this plugin in the plugin preference panel, so I have to download it from the plugin site<https://plugins.jetbrains.com/plugin/9492-smart-tomcat/versions> manually and install it from disk. And I got this error when I was trying to install it.

[image]<https://user-images.githubusercontent.com/3297602/65569369-f4175d00-df8f-11e9-996a-f0a2d2406fc3.png>

―

**Comment by zengkid** [comment] 2019-09-30 11:17
Hi, Kevin

  The root cause is Jetbrains  extracted Java functionality into a separate plugin<https://youtrack.jetbrains.com/issue/IDEA-195719> from IDEA 2019.2 version
I will build a quick fix version to fix the issue.

Regards
zengkid

发件人: Kevin Yue<mailto:notifications@github.com>
发送时间: 2019年9月25日 12:28
收件人: zengkid/SmartTomcat<mailto:SmartTomcat@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [zengkid/SmartTomcat] Version 3.0 is not comapatible with the latest IDEA community version (#26)

IDEA version

IntelliJ IDEA 2019.2.2 (Community Edition)

Build #IC-192.6603.28, built on September 6, 2019

Runtime version: 11.0.3+12-b304.56 x86_64

VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

macOS 10.14.4

GC: ParNew, ConcurrentMarkSweep

Memory: 3005M

Cores: 8

Registry: ide.mac.allowDarkWindowDecorations=true

Non-Bundled Plugins: IdeaVIM, JettyRunner-GK, com.alayouni.ansiHighlight, com.intellij.ideolog, com.your.company.unique.plugin.id, com.cybrosis.catdea, training, zielu.gittoolbox

Smart Tomcat version

Version: 3.0f

I cannot find this plugin in the plugin preference panel, so I have to download it from the plugin site<https://plugins.jetbrains.com/plugin/9492-smart-tomcat/versions> manually and install it from disk. And I got this error when I was trying to install it.

[image]<https://user-images.githubusercontent.com/3297602/65569369-f4175d00-df8f-11e9-996a-f0a2d2406fc3.png>

―

**Closed** 2019-09-30 11:55 UTC
Labels: bug
