### ISSUE TITLE
workspace.xml file has predefined_log_file excessively appended to the config.

### ISSUE THREAD

**Issue by sblatnick** [zengkid/SmartTomcat#94] opened 2022-09-23 17:44 UTC
I noted I was having performance issues with Intellij Ultimate every time I would focus/unfocus the editor.
It turned out that actions which would update the workspace.xml file were taking a long time to save because I had 1,310,724 entities in the xml:
```     <configuration name="Flexline (Smart)" type="com.poratu.idea.plugins.tomcat" factoryName="SMART_TOMCAT_FACTORY">
       <predefined_log_file enabled="true" id="Tomcat Localhost Log" />
       <predefined_log_file enabled="true" id="Tomcat Access Log" />
       <predefined_log_file id="Tomcat Catalina Log" />
       <predefined_log_file id="Tomcat Manager Log" />
       <predefined_log_file id="Tomcat Host Manager Log" />
...
```
More details can be seen with my support ticket with JetBrains: https://intellij-support.jetbrains.com/hc/en-us/community/posts/7745666082834-Linux-focus-blur-hangs-for-4-8-seconds

I'm running this on Debian Linux.

**Comment by yuezk** [comment] 2022-09-24 00:00
@sblatnick The old version of SmartTomcat could have this bug, what's your version? Suggest removing workspace.xml and using the latest SmartTomcat.

**Comment by sblatnick** [comment] 2022-09-27 13:10
Sorry, but I am unsure what version I was running because I uninstalled it.  I only discovered the issue by reviewing a diff of the workspace.xml and a new one.  From the screenshot in #81 it does look like that bug.  You can probably close this bug as a duplicate and already fixed.

**Comment by yuezk** [comment] 2022-09-27 15:23
From the workspace.xml you provided in the linked IDEA ticket, I can infer that old version of this plugin could be used, because l have removed `factoryName="SMART_TOMCAT_FACTORY"` in recent releases.

```
<configuration name="Flexline (Smart)" type="com.poratu.idea.plugins.tomcat" factoryName="SMART_TOMCAT_FACTORY">
```

Closing it for now and feel free to reopen it if it still reproducible.

**Closed by yuezk** 2022-09-27 15:23 UTC
